### ISSUE TITLE
Add support to download more than 100 files

### ISSUE THREAD

**Issue by smartjinyu** [nelenkov/gdrive-appdata#6]
Hi, thanks for the nice script to download Google Drive AppData. There is a small problem that currently it only supports download 100 files maximum. We can fix this by utilizing the `nextPageToken` returned by `service.files().list()` in line 308 - 309. Also `pageSize` can be increased to 1000.
https://github.com/nelenkov/gdrive-appdata/blob/c8de4ba230b8b99a2ad1393554157abde08837fa/get-gdrive-appdata.py#L308
https://github.com/nelenkov/gdrive-appdata/blob/c8de4ba230b8b99a2ad1393554157abde08837fa/get-gdrive-appdata.py#L309

I have made a fix on my fork. If it's OK, I can create a PR and merge it to this repo.
https://github.com/smartjinyu/gdrive-appdata/commit/00a776a2010ac4edcd1112d0651826bf863c3bf5

**Comment by nelenkov** [comment]
Hi, thanks for looking into this. I guess I never ran into the 100 file limit, but it does makes sense to try and get all the files. Your code looks fine, a PR would e appreciated.
